name: ArtisTree
favicon: null
layout_spectrum: 0.9307428218889982
typography_spectrum: 0.396277729421854
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.017717057140544057
  lightness: 0.5186630464158952
  saturation: 0.47169620217755437
  rhythmicContrast: 0.8025791065301746
purpose: []
